FRW-19 Updated symfony packeges to v6
spryker-sdk/security-checker pull request #6
Opened 2022-09-07 14:02 UTC by geega

2022-10-07 12:39 UTC, dimitriyTsemma approved these changes

2022-10-19 15:09 UTC, mstfEmkSpryker approved these changes

2022-12-08 19:09 UTC, asmarovydlo requested changes
1. Release type should be `patch (currently 0.x)`
2. Please update all PR's to have the same title as here https://github.com/spryker/spryker/pull/9610

2022-12-12 18:15 UTC, asmarovydlo approved these changes

2023-01-24 16:01 UTC, merged